#!/bin/bash

# Base folder
BASE_DIR="100_days_of_python"
mkdir -p "$BASE_DIR"

# Day titles
titles=(
  "Band Name Generator"
  "Tip Calculator"
  "Treasure Island Game"
  "Rock Paper Scissors"
  "Password Generator"
  "Reeborgs World Hurdles"
  "Hangman Game"
  "Caesar Cipher"
  "Silent Auction Program"
  "Calculator"
  "Blackjack Game"
  "Number Guessing Game"
  "Debugging Practice"
  "Higher Lower Game"
  "Coffee Machine Procedural"
  "Coffee Machine OOP"
  "Quiz Game"
  "Turtle Graphics GUI Design"
  "Etch A Sketch App"
  "Turtle Race Game"
  "Snake Game Part1"
  "Snake Game Part2"
  "Turtle Crossing Game"
  "Files And Directories"
  "US States Game"
  "NATO Alphabet Project"
  "Tkinter GUI Intro"
  "Pomodoro App"
  "Password Manager"
  "Password Manager Improvements"
  "Flashcard App Part1"
  "Flashcard App Part2"
  "API Calls ISS Tracker"
  "Kanye Quotes App"
  "Rain Alert SMS"
  "Stock Trading Alert"
  "Habit Tracker Pixela API"
  "Workout Tracker Sheety"
  "Flight Deals Finder"
  "Flight Club App"
  "Web Scraping BeautifulSoup"
  "Price Tracker Bot"
  "Email SMS Notifications"
  "Job Application Bot"
  "Web Browsing Selenium"
  "Cookie Clicker Bot"
  "Instagram Follower Bot"
  "Tinder Automation Bot"
  "LinkedIn AutoApply Bot"
  "Capstone Job Bot"
  "HTML CSS Basics"
  "Personal Site HTML CSS"
  "Bootstrap Responsive Design"
  "Personal Site Bootstrap"
  "Flask Web Server"
  "Advanced Flask Routing"
  "Blog Website"
  "Jinja Templating"
  "WTForms Flask"
  "Coffee Wifi Site"
  "REST API Flask"
  "REST API Authentication"
  "Advanced REST API"
  "Flask Login Auth"
  "Blog With Users Admin"
  "Decorators"
  "Web App Final Touches"
  "Web App Capstone"
  "Database Intro"
  "SQLite SQLAlchemy"
  "Users Login DB"
  "Advanced SQLAlchemy"
  "Flask Authentication"
  "RESTful Blog API"
  "RESTful Blog API Auth"
  "Fullstack Web App"
  "Pandas Data Science"
  "Weather Data Analysis"
  "Spotify Playlist Generator"
  "Amazon Price Tracker"
  "Automation SMTP"
  "Birthday Wisher Bot"
  "Motivational Quote Email"
  "Gmail SMTP Integration"
  "PyAutoGUI Automation"
  "Keyboard Automation"
  "Mouse Screen Automation"
  "OCR Screen Reading"
  "Image Editing Pillow"
  "File Folder Automation"
  "Final Project Planning"
  "Final Project Start"
  "Final Project Progress"
  "Final Project Progress"
  "Final Project Progress"
  "Final Project Polish"
  "Final Project Polish"
  "Final Project WrapUp"
  "Final Project Review"
  "Final Project Submission"
)

# Loop through and create folders with README.md
for i in "${!titles[@]}"; do
  day_num=$(printf "Day%03d" $((i+1)))
  title="${titles[$i]}"
  folder="${BASE_DIR}/${day_num}_$(echo "$title" | tr ' ' '_')"
  mkdir -p "$folder"

  cat > "$folder/README.md" <<EOF
# ${day_num} - ${title}

Part of the [#100DaysOfPython](https://github.com/leeuwen/100_days_of_python) challenge.

This project was built on ${day_num} of the [Angela Yu 100 Days of Python Bootcamp](https://www.udemy.com/course/100-days-of-code).

## Topics Covered
_(Add a brief list of topics or techniques used in this day's project.)_
EOF
done

echo "✅ All folders and README.md files generated!"